source/blog/urls.py
from django.urls import path
from blog.views import PostIndexView, PostView, PostAddView, PostUpdateView, PostDeleteView, CategoryPostView, \
    PostCommentCreateView, CommentUpdateView, CommentDeleteView

app_name = 'blog'

urlpatterns = [
    path('', PostIndexView.as_view(), name='index'),
    path('<str:slug>-<int:pk>/', PostView.as_view(), name='post_detail'),
    path('post/add/', PostAddView.as_view(), name='add_post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='update_post'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='delete_post'),
    path('category/<str:slug>/', CategoryPostView.as_view(), name='category'),
    path('post/<int:pk>/comment/add/', PostCommentCreateView.as_view(), name='post_comment_add'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from slugify import slugify


# Create your models here.
class Status(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Name', unique=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Name')
    slug = models.SlugField(default='', editable=False, max_length=200, null=False, unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:category", kwargs={
            'slug': self.slug,
        })


class Post(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name='Title')
    slug = models.SlugField(default='', editable=False, max_length=200, null=False)
    author = models.ForeignKey(User, related_name='posts', on_delete=models.SET_DEFAULT, default=1,
                               verbose_name="Author")
    body = models.TextField(max_length=3000, null=False, blank=False, verbose_name="Content")
    publish = models.DateTimeField(default=timezone.now, verbose_name='Publish date')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated at')
    status = models.ForeignKey('blog.Status', to_field='name', default='Draft', related_name='status',
                               on_delete=models.PROTECT, verbose_name='Status')
    category = models.ManyToManyField('blog.Category', related_name='category', verbose_name='Category')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={
            'pk': self.id,
            'slug': self.slug,
        })


class Comment(models.Model):
    text = models.TextField(max_length=400, verbose_name='Comment')
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments',
                             verbose_name="Post")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments',
                               verbose_name="Author")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")

    def __str__(self):
        return f'{self.pk}. {self.text[:20]}'

source/blog/forms.py
from django import forms
from blog.models import Post, Comment
from django.forms import widgets


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'status', 'category']
        widgets = {'category': widgets.CheckboxSelectMultiple}


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Search')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

source/blog/views/category_views.py
from django.views.generic import DetailView
from django.views.generic.list import MultipleObjectMixin
from blog.models import Post, Category


class CategoryPostView(DetailView, MultipleObjectMixin):
    template_name = 'category/category_index.html'
    model = Category
    paginate_by = 3

    def get_context_data(self, **kwargs):
        object_list = Post.objects.filter(category=self.get_object())
        context = super(CategoryPostView, self).get_context_data(object_list=object_list, **kwargs)
        categories = Category.objects.all()
        context['categories'] = categories
        return context

source/blog/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView

from blog.forms import CommentForm
from blog.models import Comment, Post


class PostCommentCreateView(LoginRequiredMixin, CreateView):
    template_name = 'comment/add_comment.html'
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.post.slug, 'pk': self.object.post.pk})

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        form.instance.post = post
        form.instance.author = self.request.user
        return super().form_valid(form)


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    model = Comment
    template_name = 'comment/update_comment.html'
    form_class = CommentForm
    context_object_name = 'comment'
    permission_required = 'blog.change_comment'

    def has_permission(self):
        return self.request.user.has_perm('webapp.change_comment') or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.post.slug, 'pk': self.object.post.pk})


class CommentDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'blog.delete_comment'
    model = Comment

    def has_permission(self):
        comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        return super().has_permission() or comment.author == self.request.user

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.post.slug, 'pk': self.object.post.pk})

source/blog/views/post_views.py
from django.shortcuts import get_object_or_404, redirect, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from django.utils.http import urlencode
from django.views.generic.list import MultipleObjectMixin

from blog.forms import PostForm, SimpleSearchForm
from blog.models import Post, Category, Comment
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin


class PostIndexView(ListView):
    template_name = 'post/post_index.html'
    context_object_name = 'posts'
    model = Post
    paginate_by = 3
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(title__icontains=self.search_value) |
                                       Q(body__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        categories = Category.objects.all()
        context['categories'] = categories
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class PostView(DetailView, MultipleObjectMixin):
    template_name = 'post/post_view.html'
    model = Post
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        comments = Comment.objects.filter(post=self.get_object())
        context = super(PostView, self).get_context_data(object_list=comments, **kwargs)
        return context


class PostAddView(LoginRequiredMixin, CreateView):
    template_name = 'post/post_add.html'
    model = Post
    form_class = PostForm
    context_object_name = 'post'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.slug, 'pk': self.object.pk})


class PostUpdateView(PermissionRequiredMixin, UpdateView):
    model = Post
    template_name = 'post/post_update.html'
    form_class = PostForm
    context_object_name = 'post'
    permission_required = 'blog.change_post'

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.slug, 'pk': self.object.pk})


class PostDeleteView(PermissionRequiredMixin, View):
    permission_required = 'blog.delete_post'

    def has_permission(self):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        return super().has_permission() or post.author == self.request.user

    def post(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        post.delete()
        return redirect('blog:index')

source/blog/templates/post/post_add.html
{% extends 'base.html' %}
{% block content %}
    <h1>Add Post</h1>

    <form action="" method="post">
        {% include 'partial/form.html' with button_text="Add" %}
    </form>
    <p>{{ error }}</p>
{% endblock %}

source/blog/templates/post/post_index.html
{% extends 'base.html' %}

{% block nav %}
    <li class="nav-item search-form">
        <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDarkDropdownMenuLink"
               data-bs-toggle="dropdown" aria-expanded="false">
                Categories
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                {% for category in categories %}
                    <li>
                        <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </li>
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:add_post' %}">Add Post</a>
        </li>
    {% endif %}

    <li class="nav-item search-form">
        {% include 'partial/simple_search.html' %}
    </li>

{% endblock %}


{% block content %}
    {% include 'partial/posts_list_partial.html' %}
{% endblock %}

source/blog/templates/post/post_update.html
{% extends 'base.html' %}
{% block content %}
    <h1>Update Post</h1>

    <form action="" method="post">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
    <p>{{ error }}</p>
{% endblock %}

source/blog/templates/post/post_view.html
{% extends "base.html" %}

{% block nav %}
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:post_comment_add' post.pk %}">Add Comment</a>
        </li>
    {% endif %}
{% endblock %}


{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="bg-light my-3">
            <h1>{{ post.title }}
                {% if perms.blog.change_post or post.author == request.user %}
                     <a href="{% url 'blog:update_post' post.pk %}" class="btn btn-success">
                         <i class="bi bi-pencil-square"></i>
                     </a>
                {% endif %}
                {% if perms.blog.delete_post or post.author == request.user %}
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
                        <i class="bi bi-trash3"></i>
                    </button>
                {% endif %}
            </h1>
            <p>
                Published {{ post.publish }}
                by
                <a class="text-secondary" href="{{ post.author.profile.get_absolute_url }}">
                    {{ post.author }}
                </a>
            </p>
            <p>
                <b>Categories:</b>
                {% for category in post.category.all %}
                    {{ category.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
        </div>
        <hr>
        <div class="mx-4">
            <p>{{ post.body|linebreaks }}</p>
        </div>
    </div></br>

    {% include 'partial/delete_post_modal.html' %}
        <h3 class="ms-3">Comments:</h3>
    <div class="row">
        {% for comment in object_list %}
            <div class="col-sm-4">
                <div class="card text-bg-light mb-3">
                    <div class="card-header">
                        <h4>
                            <a class="text-secondary" href="{{ comment.author.profile.get_absolute_url }}">{{ comment.author }}</a>
                        </h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ comment.text }}</p>

                        <div class="d-flex justify-content-around">
                            {% if perms.blog.change_comment or comment.author == request.user %}
                                <a href="{% url 'blog:comment_update' comment.pk %}"
                                   class="btn btn-success px-5">Update</a>
                            {% endif %}
                            {% if perms.webapp.delete_comment or comment.author == request.user %}
                                <a href="{% url 'blog:comment_delete' comment.pk %}"
                                   class="btn btn-danger px-5">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>No comments</p>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}