source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<str:slug>/', UserDetailView.as_view(), name='detail'),
    path('<str:slug>/change/', UserChangeView.as_view(), name='change'),
    path('<str:slug>/password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

source/blog/urls.py
from django.urls import path
from blog.views import PostIndexView, PostView, PostAddView, PostUpdateView, PostDeleteView, CategoryPostView, \
    PostCommentCreateView, CommentUpdateView, CommentDeleteView

app_name = 'blog'

urlpatterns = [
    path('', PostIndexView.as_view(), name='index'),
    path('<str:slug>-<int:pk>/', PostView.as_view(), name='post_detail'),
    path('post/add/', PostAddView.as_view(), name='add_post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='update_post'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='delete_post'),
    path('category/<str:slug>/', CategoryPostView.as_view(), name='category'),
    path('post/<int:pk>/comment/add/', PostCommentCreateView.as_view(), name='post_comment_add'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE,
                                verbose_name='User')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Birth date')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_avatar', verbose_name='Avatar')
    github = models.URLField(null=True, blank=True, verbose_name='GitHub')
    bio = models.TextField(null=True, blank=True, verbose_name='Bio')

    def __str__(self):
        return f"{self.user.username} 's Profile"

    def get_absolute_url(self):
        return reverse("accounts:detail", kwargs={
            'slug': self.user.username,
        })

    class Meta:
        db_table = 'profile'
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

source/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django import forms
from accounts.models import Profile


class MyUserCreationForm(forms.ModelForm):
    password = forms.CharField(label="Password", strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Confirm Password", required=True, widget=forms.PasswordInput, strip=False)
    email = forms.EmailField(label='Email', required=True)

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if not first_name and not last_name:
            raise forms.ValidationError('Fill in at least one field!')
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords do not match!')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'First name', 'last_name': 'Last name', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'bio', 'github']

source/accounts/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView
from django.views.generic.list import MultipleObjectMixin
from accounts.models import Profile
from blog.models import Post
from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm
from django.contrib.auth.models import User


class RegisterView(CreateView):
    model = User
    form_class = MyUserCreationForm
    template_name = 'registration.html'

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url

        next_url = self.request.POST.get('next')
        if next_url:
            return next_url

        return reverse('blog:index')


class UserDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_by = 3
    slug_field = 'username'

    def get_context_data(self, **kwargs):
        object_list = Post.objects.filter(author=self.get_object())
        return super().get_context_data(object_list=object_list, **kwargs)


class UserChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'
    form_profile_class = ProfileChangeForm
    slug_field = 'username'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'profile_form' not in kwargs:
            context['profile_form'] = self.form_profile_class(instance=self.get_object().profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.form_profile_class(instance=self.get_object().profile, data=request.POST,
                                               files=request.FILES)
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        return self.render_to_response(self.get_context_data(form=form, profile_form=profile_form))

    def get_success_url(self):
        return reverse("accounts:detail", kwargs={
            'slug': self.get_object().username,
        })


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'password_change.html'

    def get_success_url(self):
        return reverse("accounts:detail", kwargs={
            'slug': self.get_object().username,
        })

source/accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center">Login</h1>
    <form action="" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="text-danger">The username or password is not correct.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Username:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Password:</label>
            <input type="password" name="password" id="password">
        </div>
        <p>
            Don't have an account?
            <a class href="{% url 'accounts:create'%}?next={{ request.get_full_path }}">Register</a>
        </p>
        <button type="submit" class="btn btn-secondary px-5">Login</button>
    <input type="hidden" name="next" value="{{ next }}" />
    </form>


{% endblock %}

source/accounts/templates/password_change.html
{% extends 'base.html' %}
{% block content %}
    <h1>Change password</h1>

    <form action="" method="post">
        {% include 'partial/form.html' with button_text="Change" %}

    </form>
{% endblock %}

source/accounts/templates/registration.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block content %}
   <h1>Registration</h1>

    <form action="" method="post">
        {% include 'partial/form.html' with button_text="Register" %}
        <input type="hidden" name="next" value="{{ next_url }}" />
    </form>
    <p>{{ error }}</p>
{% endblock %}

source/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block content %}
    <h1>Change personal data</h1>

    <form action="" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with fields_only=True %}
        {% include 'partial/form.html' with form=profile_form button_text="Change"%}

    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block nav %}
    {% if request.user == user_obj %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:change' user_obj.username %}">Edit </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:password_change' user_obj.username %}">Change password</a>
    </li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Profile {{ user_obj.get_full_name|default:user_obj.username }}</h1>

    <div class="card mb-3">
        <div class="row g-0">
            {% if user_obj.profile.avatar %}
                <div class="col-md-4">
                    <img src="{{ user_obj.profile.avatar.url }}" class="img-fluid rounded-start w-75" alt="avatar">
                </div>
            {% endif %}
            <div class="col-md-8">
                <div class="card-body">
                    <h3 class="card-title fw-bold">{{ user_obj.username }}</h3>

                    <p class="card-text">
                        {% if user_obj.first_name %}
                            {{ user_obj.first_name }}
                        {% endif %}
                        {% if user_obj.last_name %}
                            {{ user_obj.last_name }}
                        {% endif %}
                    </p>
                    <p class="card-text">
                        {% if user_obj.profile.bio %}
                            {{ user_obj.profile.bio }}
                        {% endif %}
                    </p>
                    {% if user_obj.profile.birth_date %}
                        <p class="card-text">Birth Date:
                            {{ user_obj.profile.birth_date }}
                        </p>
                    {% endif %}

                    <p class="card-text">Email: {{ user_obj.email }}</p>

                    <p class="fs-4">
                        {% if user_obj.profile.github %}
                            <a class="text-dark" href="{{ user_obj.profile.github }}"><i class="bi bi-github"></i></a>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>

    {% include 'partial/posts_list_partial.html' with posts=object_list %}
{% endblock %}