source/blog/urls.py
from django.urls import path
from blog.views import PostIndexView, PostView, PostAddView, PostUpdateView, PostDeleteView, CategoryPostView, \
    PostCommentCreateView, CommentUpdateView, CommentDeleteView

app_name = 'blog'

urlpatterns = [
    path('', PostIndexView.as_view(), name='index'),
    path('<str:slug>-<int:pk>/', PostView.as_view(), name='post_detail'),
    path('post/add/', PostAddView.as_view(), name='add_post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='update_post'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='delete_post'),
    path('category/<str:slug>/', CategoryPostView.as_view(), name='category'),
    path('post/<int:pk>/comment/add/', PostCommentCreateView.as_view(), name='post_comment_add'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from slugify import slugify


# Create your models here.
class Status(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Name', unique=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Name')
    slug = models.SlugField(default='', editable=False, max_length=200, null=False, unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:category", kwargs={
            'slug': self.slug,
        })


class Post(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name='Title')
    slug = models.SlugField(default='', editable=False, max_length=200, null=False)
    author = models.ForeignKey(User, related_name='posts', on_delete=models.SET_DEFAULT, default=1,
                               verbose_name="Author")
    body = models.TextField(max_length=3000, null=False, blank=False, verbose_name="Content")
    publish = models.DateTimeField(default=timezone.now, verbose_name='Publish date')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated at')
    status = models.ForeignKey('blog.Status', to_field='name', default='Draft', related_name='status',
                               on_delete=models.PROTECT, verbose_name='Status')
    category = models.ManyToManyField('blog.Category', related_name='category', verbose_name='Category')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={
            'pk': self.id,
            'slug': self.slug,
        })


class Comment(models.Model):
    text = models.TextField(max_length=400, verbose_name='Comment')
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments',
                             verbose_name="Post")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments',
                               verbose_name="Author")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")

    def __str__(self):
        return f'{self.pk}. {self.text[:20]}'

source/blog/forms.py
from django import forms
from blog.models import Post, Comment
from django.forms import widgets


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'status', 'category']
        widgets = {'category': widgets.CheckboxSelectMultiple}


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Search')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

source/blog/views/category_views.py
from django.views.generic import DetailView
from django.views.generic.list import MultipleObjectMixin
from blog.models import Post, Category


class CategoryPostView(DetailView, MultipleObjectMixin):
    template_name = 'category/category_index.html'
    model = Category
    paginate_by = 3

    def get_context_data(self, **kwargs):
        object_list = Post.objects.filter(category=self.get_object())
        context = super(CategoryPostView, self).get_context_data(object_list=object_list, **kwargs)
        categories = Category.objects.all()
        context['categories'] = categories
        return context

source/blog/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView

from blog.forms import CommentForm
from blog.models import Comment, Post


class PostCommentCreateView(LoginRequiredMixin, CreateView):
    template_name = 'comment/add_comment.html'
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.post.slug, 'pk': self.object.post.pk})

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        form.instance.post = post
        form.instance.author = self.request.user
        return super().form_valid(form)


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    model = Comment
    template_name = 'comment/update_comment.html'
    form_class = CommentForm
    context_object_name = 'comment'
    permission_required = 'blog.change_comment'

    def has_permission(self):
        return self.request.user.has_perm('webapp.change_comment') or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.post.slug, 'pk': self.object.post.pk})


class CommentDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'blog.delete_comment'
    model = Comment

    def has_permission(self):
        comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        return super().has_permission() or comment.author == self.request.user

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.post.slug, 'pk': self.object.post.pk})

source/blog/views/post_views.py
from django.shortcuts import get_object_or_404, redirect, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from django.utils.http import urlencode
from django.views.generic.list import MultipleObjectMixin

from blog.forms import PostForm, SimpleSearchForm
from blog.models import Post, Category, Comment
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin


class PostIndexView(ListView):
    template_name = 'post/post_index.html'
    context_object_name = 'posts'
    model = Post
    paginate_by = 3
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(title__icontains=self.search_value) |
                                       Q(body__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        categories = Category.objects.all()
        context['categories'] = categories
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class PostView(DetailView, MultipleObjectMixin):
    template_name = 'post/post_view.html'
    model = Post
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        comments = Comment.objects.filter(post=self.get_object())
        context = super(PostView, self).get_context_data(object_list=comments, **kwargs)
        return context


class PostAddView(LoginRequiredMixin, CreateView):
    template_name = 'post/post_add.html'
    model = Post
    form_class = PostForm
    context_object_name = 'post'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.slug, 'pk': self.object.pk})


class PostUpdateView(PermissionRequiredMixin, UpdateView):
    model = Post
    template_name = 'post/post_update.html'
    form_class = PostForm
    context_object_name = 'post'
    permission_required = 'blog.change_post'

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.slug, 'pk': self.object.pk})


class PostDeleteView(PermissionRequiredMixin, View):
    permission_required = 'blog.delete_post'

    def has_permission(self):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        return super().has_permission() or post.author == self.request.user

    def post(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        post.delete()
        return redirect('blog:index')

source/blog/templates/partial/delete_post_modal.html
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Are you sure want to delete "{{ post.title }}"?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-footer">
                <form method="POST" action="{% url "blog:delete_post" post.pk %}" class="text-center">
                    {% csrf_token %}
                    <input class="btn btn-secondary" type="submit" value="Confirm">
                    <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

source/blog/templates/partial/form.html
{% if not fields_only %}
    {% csrf_token %}
{% endif %}

{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <div class="form-check">
        <p>
            <label for="{{ field.id_for_label }}">
                {{ field.label }}
            </label>
        </p>
        <p class="w-50">{{ field }}</p>
        {% for error in field.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}


{% if not fields_only %}
<div class="form-check">
    <input type="submit" class="btn btn-secondary px-5" value="{{ button_text }}"/>
</div>
{% endif %}

source/blog/templates/partial/pagination.html
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if not page_obj.has_previous %}
            <li class="page-item disabled">
                <a class="page-link">&laquo; To begin</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link">Back</a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link border-secondary bg-light text-dark" href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; To begin</a>
            </li>
            <li class="page-item">
                <a class="page-link bg-light text-dark"
                   href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Back</a>
            </li>
            <li class="page-item">
                <a class="page-link bg-light text-dark" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">
                    {{ page_obj.previous_page_number }}
                </a>
            </li>
        {% endif %}

        <li class="page-item active text-secondary" aria-current="page">
            <form method="get">
                {% if search %}<input type="hidden" name="search" value="{{ search }}">{% endif %}
                <input type="text" class="form-control" name="page" value="{{ page_obj.number }}">
            </form>
        </li>

        {% if not page_obj.has_next %}
            <li class="page-item disabled">
                <a class="page-link">Next</a>
            </li>

            <li class="page-item disabled">
                <a class="page-link">To the end &raquo;</a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link bg-light text-dark border-secondary" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">
                    {{ page_obj.next_page_number }}
                </a>
            </li>
            <li class="page-item">
                <a class="page-link bg-light text-dark border-secondary" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link bg-light text-dark border-secondary"
                   href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">To the end
                    &raquo;</a>

            </li>
        {% endif %}
    </ul>
</div>

source/blog/templates/partial/posts_list_partial.html
<h1>Posts</h1>
    <div class="row">
        {% for post in posts %}
            <div class="col-sm-4 my-3">
                <div class="card">
                    <div class="card-header bg-secondary text-white">
                        <h3 class="card-title">{{ post.title }}</h3>
                    </div>
                    <div class="card-body">
                        <p>
                            Published {{ post.publish }}
                            by
                            <a class="text-secondary" href="{{ post.author.profile.get_absolute_url }}">
                                {{ post.author }}
                            </a>
                        </p>
                        <p class="card-text">
                            {{ post.body|truncatewords:20|linebreaks }}
                        </p>
                        <a href="{{ post.get_absolute_url }} " class="btn btn-secondary">more</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div></br>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}

source/blog/templates/partial/simple_search.html
<form class="d-flex" role="search" action="" method="GET">
    <div>
        {{ form.search }}
        <input type="submit" class="btn btn-light ms-1" value="Search">
    </div>
    {% for error in form.search.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
</form>

{#<form class="form-inline my-2 my-lg-0">#}
{#      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
{#      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#    </form>#}